# This is a basic workflow to help you get started with Actions

name: Bicep - FLIFO Function

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
    - 'eahubops-talon/flifoaa/function_app/**'
    - '.github/workflows/Bicep - FLIFO Function.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'eahubops-talon/flifoaa/function_app/**'
    - '.github/workflows/Bicep - FLIFO Function.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # =====================
  # REPO AND AZURE AUTH
  # =====================
  Deploy_Bicep_Infra:
    #name: 
    
    # requires X job to complete first
    #needs: 
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 'NonProd'
    env:
      AZURE_FLIFO_FUNCTION_RG: rgn-n-zeaus-rgnoccint-poc-rg
    
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3 # Checks out the repository
      #with:
        #path: repo
    - run: |
        echo Working Dir ${{ github.workspace }}
        pwd
        ls -lta
        cd ..
        pwd
        ls -lta
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TAIL_NonProd }}
        
    # =====================
    # FLIFO
    # =====================
    - name: Deploy FLIFO Function Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.TAIL_NonProd_SubscriptionID }}
        resourceGroupName: ${{ env.AZURE_FLIFO_FUNCTION_RG }}
        template: eahubops-talon/flifoaa/function_app/main.bicep
        #parameters: ./eahubops-talon/flifoaa/function_app/parameters.json
        failOnStdErr: false
