# This is a basic workflow to help you get started with Actions

name: Bicep - Deploy Stages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths:
    - 'eahubops-talon/flifoaa/function_app/**'
    - 'eahubops-talon/flifoaa/service_bus/**'
    - '.github/workflows/Bicep - Deploy Stages.yml'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'eahubops-talon/flifoaa/function_app/**'
    - 'eahubops-talon/flifoaa/service_bus/**'
    - '.github/workflows/Bicep - Deploy Stagess.yml'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  changes-run-check:
    runs-on: ubuntu-latest
    outputs:
      sbus: ${{ steps.changes.outputs.sbus }}
      func: ${{ steps.changes.outputs.func }}
    steps:
    - uses: actions/checkout@v3
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          sbus:
            - 'eahubops-talon/flifoaa/service_bus/**'
          func:
            - 'eahubops-talon/flifoaa/function_app/**'

  # =====================
  # Deploy Infra
  # =====================
  Deploy_Service_Bus:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 'NonProd'
    env:
      AZURE_SERVICE_BUS_RG: rgn-n-zeaus-rgnoccint-poc-rg
    
    # Wait from the paths-filter to be completed before starting next-job
    needs: changes-run-check
    if: ${{ needs.changes-run-check.outputs.sbus == 'true' }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3 # Checks out the repository
    - run: |
        echo Working Dir ${{ github.workspace }}
        pwd
        ls -lta
        cd ..
        pwd
        ls -lta
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TAIL_NonProd }}
        
    # =====================
    # SERVICE BUS
    # =====================
    - name: Deploy Service Bus Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.TAIL_NonProd_SubscriptionID }}
        resourceGroupName: ${{ env.AZURE_SERVICE_BUS_RG }}
        template: eahubops-talon/service_bus/main.bicep
        failOnStdErr: false
          
  Deploy_FLIFO_Function:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: 'NonProd'
    env:
      AZURE_FLIFO_FUNCTION_RG: rgn-n-zeaus-rgnoccint-poc-rg
    
    # Wait from the paths-filter to be completed before starting next-job
    needs: changes-run-check
    if: ${{ needs.changes-run-check.outputs.func == 'true' }}

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3 # Checks out the repository
    - run: |
        echo Working Dir ${{ github.workspace }}
        pwd
        ls -lta
        cd ..
        pwd
        ls -lta
    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.TAIL_NonProd }}
        
    # =====================
    # FLIFO
    # =====================
    - name: Deploy FLIFO Function Bicep
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.TAIL_NonProd_SubscriptionID }}
        resourceGroupName: ${{ env.AZURE_FLIFO_FUNCTION_RG }}
        template: eahubops-talon/flifoaa/function_app/main.bicep
        #parameters: ./eahubops-talon/flifoaa/function_app/parameters.json
        failOnStdErr: false
